-- signup_tokens: one-time tokens generated by admin for student account creation
CREATE TABLE IF NOT EXISTS public.signup_tokens (
  id             uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  token          text        UNIQUE NOT NULL,
  created_at     timestamptz DEFAULT now() NOT NULL,
  expires_at     timestamptz NOT NULL,
  used_at        timestamptz,
  used_by        uuid        REFERENCES public.profiles(id) ON DELETE SET NULL,
  used_by_email  text,
  created_by     uuid        REFERENCES public.profiles(id) NOT NULL
);

ALTER TABLE public.signup_tokens ENABLE ROW LEVEL SECURITY;

-- Admins have full access
CREATE POLICY "admins_all_on_signup_tokens"
  ON public.signup_tokens
  FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );
